version: "3"

services:
    client:
        image: nginx
        restart: always
        container_name: nginx_8000
        ports:
            - 8000:80
        volumes:
            - ./src:/usr/share/nginx/html